# Generated by Django 3.2.25 on 2025-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
