import random

def evaluate_fit(image_path):
    fit_descriptions = [
        "Well-fitted around the torso and legs.",
        "Slightly loose on the shoulders.",
        "Tight-fitting; may restrict comfort.",
        "Perfectly tailored to body shape.",
        "Relaxed fit that enhances casual vibe.",
        "Oversized fit adds a stylish streetwear edge.",
        "Snug fit on arms, slightly tight on chest.",
        "Smart fit with good tapering around the waist.",
        "Loose fit contributes to a comfortable silhouette.",
        "Fitted sleeves, but boxy torso cut.",
        "Slim-fit design works well with this outfit style.",
        "Baggy fit offers a 90s retro appeal.",
        "Well-structured shoulder seams suggest good tailoring.",
        "Poor drape—fabric bunches near the waist.",
        "Flattering fit that elongates the body frame.",
        "Pants are too long, creating a sloppy look.",
        "Jacket fits well, but sleeves are slightly long.",
        "Top hugs the body comfortably.",
        "Fit gives a balanced and proportional silhouette.",
        "Slight mismatch between upper and lower garment sizing.",
        "Fitted in all the right places—great styling.",
        "Loose hem makes the outfit appear unfinished.",
        "The shirt is too short for the overall look.",
        "Trousers cinch slightly too much at the waist.",
        "Fit reflects attention to modern cuts and style.",
        "Garment appears tailored but not restrictive.",
        "Jacket drapes cleanly—a sign of good construction.",
        "Slight bulging near buttons—may be too tight.",
        "Pants gather at the ankle—intentional jogger style.",
        "Tapered ends give a refined look to the pants.",
        "Outfit shapes the torso well and supports posture.",
        "Fitted neckline complements the face structure.",
        "Hips appear slightly constrained by fit.",
        "Outfit fit gives an athletic look overall.",
        "Outfit appears too boxy; lacks natural shape.",
        "Drape of the fabric enhances the silhouette.",
        "Relaxed waistband balances snug upper fit.",
        "Tight collar reduces comfort slightly.",
        "Garment contours to the body elegantly.",
        "Drop shoulder design gives a fashion-forward look.",
        "Bottom fit contrasts well with the top silhouette.",
        "Shoulder seams droop slightly, creating a slouchy effect.",
        "Outfit fit is stylish but might need minor adjustments.",
        "Excellent balance between fitted and relaxed components.",
        "Blazer cut accentuates the V-shape torso well.",
        "Length of the outfit parts is ideal for body ratio.",
        "Tight armholes restrict arm movement slightly.",
        "Well-fitted outfit adds to confidence and presence.",
        "Unstructured fit provides a casual and easygoing tone.",
        "Imbalanced fit between chest and waist could be refined.",
        "Smooth lines from top to bottom indicate quality fit.",
        "Fit aligns with current fashion silhouettes and preferences."
    ]

    score = round(random.uniform(6.0, 9.5), 1)
    reason = random.choice(fit_descriptions)
    return score, reason
